version: 2
jobs:
  build:
    docker:
      - image: katalonstudio/katalon-circleci
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: |
            KATALON_OPTS ='-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'
            $KATALON_KATALON_ROOT_DIR/scripts/katalon-execute.sh